### ISSUE TITLE
cron jobs broken

### ISSUE THREAD

**Issue by dpizarroeduca** [hanneshal/otrs4-docker#7]
The file **/opt/otrs/var/cron/Znuny4OTRS-Repo.opm** is not excluded by the rule found in **/opt/otrs/bin/Cron.sh**:

```bash
if mkdir -p $CRON_DIR; cd $CRON_DIR && ls -d * | grep -v '.dist'| grep -v '.rpm'
````

So the tmp cron job created when doing
```bash
/opt/otrs/bin/Cron.sh start
```
appends the contents of the xml file, and breaks cron.

I guess it should be 
```bash
if mkdir -p $CRON_DIR; cd $CRON_DIR && ls -d * | grep -v '.dist'| grep -v '.opm'
````

**Comment by hanneshal** [comment]
Hey Diego,

we need to move the file. Because I don't wan't to change the default Files.

Thx for the hint!

**Comment by hanneshal** [comment]
fixed with latest commit.
